blank_issues_enabled: true
contact_links:
  - name: Processing Issues & Feature Requests
    url: https://github.com/processing/processing4/issues/new/choose
    about: Report bugs, suggest features, or provide feedback for Processing 4.