name: Issue to Pull Request
on:
  issues:
    types:
      - opened
      - edited
      - reopened
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      props: ${{ steps.parseProps.outputs.props }}
    steps:
      - name: Parse issue
        id: parseIssue
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ github.event.issue.number }}

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Read and validate properties txt file
        id: parseProps
        run: >
          python -u scripts/parse_and_validate_properties_txt.py \
            ${{ fromJson(steps.parseIssue.outputs.payload).contribution_type }} \
            "${{ fromJson(steps.parseIssue.outputs.payload).properties_url }}"
  create-pr:
    needs: validate
    env:
      BRANCH_NAME: issue-${{ github.event.issue.number }}
      ISSUE_NUM: ${{ github.event.issue.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: edit database
        run: |
          cd scripts
          python add_new_contribution_to_yaml.py '${{ needs.validate.outputs.props }}'

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: new contribution from issue $ISSUE_NUM
          branch: $BRANCH_NAME
          create_branch: true
          add_options: '-u'

      - name: Create pull request
        run: gh pr create -B main -H $BRANCH_NAME --title "new contribution issue $ISSUE_NUM" --body "${{github.event.issue.title }}"
        env:
          GH_TOKEN: ${{ github.token }}
